language: ruby
bundler_args: --without development
rvm:
  - 2.2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

# jdk:
#   - oraclejdk7
#   - openjdk7

env: CI="travis"

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head

services:
  - mongodb

script: "bundle exec rspec"

sudo: false